import React from 'react';
import Head from "next/head";
import { Button, theme } from 'antd';
import { Flex, Layout, Menu } from 'antd';
import SimpleForm from '../components/SimpleForm';
import { TonConnectButton } from "@tonconnect/ui-react";
import TonConnectForm from "@/components/TonConnectForm";

const { Header, Footer, Sider, Content } = Layout;

const HomePage: React.FC = () => {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex gap="middle" wrap>
        <Layout>
          <Header>
          <div style={{display:'flex', flexDirection:'row-reverse', height:'100%', alignItems:'center'}}>
            <TonConnectButton />
          </div>
          </Header>
          <Content>
            <div style={{maxWidth: '800px', background:colorBgContainer,borderRadius: borderRadiusLG,
              padding: '12px 24px', margin: '12px auto'}}>
              <TonConnectForm />
            </div>
          </Content>
          <Footer style={{ textAlign: 'center' }}>
            Demo app
          </Footer>
        </Layout>
      </Flex>
    </>
  );
};

export default HomePage;
